name: Fastlane Metadata
on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
    paths:
      - "fastlane/**"
      - ".github/workflows/fastlane-metadata.yaml"
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
    paths:
      - "fastlane/**"
      - ".github/workflows/fastlane-metadata.yaml"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
